# Experimental makefile

COMPRESS=../shrinkle.sh

SOURCES=\
	bin/activision\ pro \
	bin/aprosys \
	bin/chiptracker \
	bin/david\ whittaker \
	bin/eaglestone \
	bin/earache \
	bin/face\ the\ music \
	bin/in\ stereo\ 1.0 \
	bin/in\ stereo\ 2.0 \
	bin/jason\ brooke \
	bin/jason\ page \
	bin/jeroen\ tel \
	bin/jochen\ hippel\ 7v \
	bin/jochen\ hippel\ st \
	bin/kris\ hatlelid \
	bin/mark\ cooksey \
	bin/maxtrax \
	bin/mugician\ ii \
	bin/mugician.amp \
	bin/musicmaker4 \
	bin/musicmaker8 \
	bin/quartet \
	bin/quartet\ st \
	bin/richard\ joseph \
	bin/richard\ joseph\ player \
	bin/rob\ hubbard \
	bin/rob\ hubbard\ 2 \
	bin/sonix\ music\ driver \
	bin/soundcontrol \
	bin/special\ fx \
	bin/steve\ turner \
	bin/synth\ 4.0 \
	bin/synth\ pack \
	bin/syntracker \
	bin/tcb\ tracker \
	bin/tim\ follin\ ii \
	bin/tme \
	bin/wally\ beben \
	bin/sound\ master \
	bin/soprol

COMPRESSED_TARGETS=\
	shr/activision\ pro.shr \
	shr/aprosys.shr \
	shr/chiptracker.shr \
	shr/david\ whittaker.shr \
	shr/eaglestone.shr \
	shr/earache.shr \
	shr/face\ the\ music.shr \
	shr/in\ stereo\ 1.0.shr \
	shr/in\ stereo\ 2.0.shr \
	shr/jason\ brooke.shr \
	shr/jason\ page.shr \
	shr/jeroen\ tel.shr \
	shr/jochen\ hippel\ 7v.shr \
	shr/jochen\ hippel\ st.shr \
	shr/kris\ hatlelid.shr \
	shr/mark\ cooksey.shr \
	shr/maxtrax.shr \
	shr/mugician\ ii.shr \
	shr/mugician.amp.shr \
	shr/musicmaker4.shr \
	shr/musicmaker8.shr \
	shr/quartet.shr \
	shr/quartet\ st.shr \
	shr/richard\ joseph.shr \
	shr/richard\ joseph\ player.shr \
	shr/rob\ hubbard.shr \
	shr/rob\ hubbard\ 2.shr \
	shr/sonix\ music\ driver.shr \
	shr/soundcontrol.shr \
	shr/special\ fx.shr \
	shr/steve\ turner.shr \
	shr/synth\ 4.0.shr \
	shr/synth\ pack.shr \
	shr/syntracker.shr \
	shr/tcb\ tracker.shr \
	shr/tim\ follin\ ii.shr \
	shr/tme.shr \
	shr/wally\ beben.shr \
	shr/sound\ master.shr \
	shr/soprol.shr

all: shr $(COMPRESSED_TARGETS)

shr:
	mkdir -p shr

clean:
	rm -f $(COMPRESSED_TARGETS) 

shr/activision\ pro.shr:          bin/activision\ pro
	$(COMPRESS) "$<" "$@"
shr/aprosys.shr:                  bin/aprosys
	$(COMPRESS) "$<" "$@"
shr/chiptracker.shr:              bin/chiptracker
	$(COMPRESS) "$<" "$@"
shr/david\ whittaker.shr:         bin/david\ whittaker
	$(COMPRESS) "$<" "$@"
shr/eaglestone.shr:               bin/eaglestone
	$(COMPRESS) "$<" "$@"
shr/earache.shr:                  bin/earache
	$(COMPRESS) "$<" "$@"
shr/face\ the\ music.shr:         bin/face\ the\ music
	$(COMPRESS) "$<" "$@"
shr/in\ stereo\ 1.0.shr:          bin/in\ stereo\ 1.0
	$(COMPRESS) "$<" "$@"
shr/in\ stereo\ 2.0.shr:          bin/in\ stereo\ 2.0
	$(COMPRESS) "$<" "$@"
shr/jason\ brooke.shr:            bin/jason\ brooke
	$(COMPRESS) "$<" "$@"
shr/jason\ page.shr:              bin/jason\ page
	$(COMPRESS) "$<" "$@"
shr/jeroen\ tel.shr:              bin/jeroen\ tel
	$(COMPRESS) "$<" "$@"
shr/jochen\ hippel\ 7v.shr:       bin/jochen\ hippel\ 7v
	$(COMPRESS) "$<" "$@"
shr/jochen\ hippel\ st.shr:       bin/jochen\ hippel\ st
	$(COMPRESS) "$<" "$@"
shr/kris\ hatlelid.shr:           bin/kris\ hatlelid
	$(COMPRESS) "$<" "$@"
shr/mark\ cooksey.shr:            bin/mark\ cooksey
	$(COMPRESS) "$<" "$@"
shr/maxtrax.shr:                  bin/maxtrax
	$(COMPRESS) "$<" "$@"
shr/mugician\ ii.shr:             bin/mugician\ ii
	$(COMPRESS) "$<" "$@"
shr/mugician.amp.shr:             bin/mugician.amp
	$(COMPRESS) "$<" "$@"
shr/musicmaker4.shr:              bin/musicmaker4
	$(COMPRESS) "$<" "$@"
shr/musicmaker8.shr:              bin/musicmaker8
	$(COMPRESS) "$<" "$@"
shr/quartet.shr:                  bin/quartet
	$(COMPRESS) "$<" "$@"
shr/quartet\ st.shr:              bin/quartet\ st
	$(COMPRESS) "$<" "$@"
shr/richard\ joseph.shr:          bin/richard\ joseph
	$(COMPRESS) "$<" "$@"
shr/richard\ joseph\ player.shr:  bin/richard\ joseph\ player                         
	$(COMPRESS) "$<" "$@"
shr/rob\ hubbard.shr:             bin/rob\ hubbard
	$(COMPRESS) "$<" "$@"
shr/rob\ hubbard\ 2.shr:          bin/rob\ hubbard\ 2
	$(COMPRESS) "$<" "$@"
shr/sonix\ music\ driver.shr:     bin/sonix\ music\ driver
	$(COMPRESS) "$<" "$@"
shr/soundcontrol.shr:             bin/soundcontrol
	$(COMPRESS) "$<" "$@"
shr/special\ fx.shr:              bin/special\ fx
	$(COMPRESS) "$<" "$@"
shr/steve\ turner.shr:            bin/steve\ turner
	$(COMPRESS) "$<" "$@"
shr/synth\ 4.0.shr:               bin/synth\ 4.0
	$(COMPRESS) "$<" "$@"
shr/synth\ pack.shr:              bin/synth\ pack
	$(COMPRESS) "$<" "$@"
shr/syntracker.shr:               bin/syntracker
	$(COMPRESS) "$<" "$@"
shr/tcb\ tracker.shr:             bin/tcb\ tracker
	$(COMPRESS) "$<" "$@"
shr/tim\ follin\ ii.shr:          bin/tim\ follin\ ii
	$(COMPRESS) "$<" "$@"
shr/tme.shr:                      bin/tme
	$(COMPRESS) "$<" "$@"
shr/wally\ beben.shr:             bin/wally\ beben
	$(COMPRESS) "$<" "$@"
shr/sound\ master.shr:            bin/sound\ master
	$(COMPRESS) "$<" "$@"
shr/soprol.shr:                      bin/soprol
	$(COMPRESS) "$<" "$@"
