	IFND LIBRARIES_AMIGUS_LIB_I
LIBRARIES_AMIGUS_LIB_I SET 1

	IFND    EXEC_LIBRARIES_I
	include "exec/libraries.i"
	ENDC

	LIBINIT

	LIBDEF _LVOAmiGUS_FindCard
	LIBDEF _LVOAmiGUS_ReserveCard
	LIBDEF _LVOAmiGUS_FreeCard
	LIBDEF _LVOAmiGUS_InstallInterrupt
	LIBDEF _LVOAmiGUS_RemoveInterrupt

	ENDC ; LIBRARIES_AMIGUS_LIB_I
